const { verifySignUp } = require("../middleware");
const controller = require("../controllers/auth.controller");
let upload = require('../config/multer.config.js');
const fileWorker = require('../controllers/file.controller.js');
// const upload = require("../middleware/upload");
// const uploadController = require("../controllers/upload");
// var fs = require('fs');
// var multer  = require('multer');
//var upload = multer({ dest: 'uploads/' }); //setting the default folder for multer
//var multer  = require('multer');
//var upload = multer({ dest: '' });

// const storage = multer.diskStorage({
//   destination(req, file, callback) {
//     callback(null, '/resources/static/assets/uploads/');
//   },
//   filename(req, file, callback) {
//     callback(null, `${file.fieldname}_${Date.now()}_${file.originalname}`);
//   },
// });

// const upload = multer({ storage });

module.exports = function(app) {
  app.use(function(req, res, next) {
    res.header(
      "Access-Control-Allow-Headers",
      "x-access-token, Origin, Content-Type, Accept"
    );
    next();
  });

  app.post(
    "/api/auth/signup",
    upload.single('fileData'),
    // [
    //   verifySignUp.checkDuplicateUsernameOrEmail,
    //   verifySignUp.checkRolesExisted
    // ],
    controller.signup
  );

  // app.post(
  //   "/api/auth/adminsignup",
  //   [
  //     verifySignUp.checkDuplicateUsernameOrEmail,
  //     verifySignUp.checkRolesExisted
  //   ],
  //   controller.adminsignup
  // );

  // app.post(
  //   "/api/auth/signup",controller.signup
  // );

  app.post("/api/auth/signin", controller.signin);


  app.post("/api/auth/finduserid", controller.findfromuserid);

  app.post("/api/auth/forimages", upload.single('fileData'),controller.forimages);

  //app.post("/api/auth/addproduct",controller.addProduct);

  app.post('/api/file/upload', upload.single('fileData'), controller.addProduct);

  app.post('/api/auth/forlocationtables', controller.forlocationtables);
  

  // app.post('/api/file/upload', upload.single("photo"), (req, res) => {
  //   console.log('file', req.files);
  //   console.log('body', req.body);
  //   res.status(200).json({
  //     message: 'success!',
  //   });
  // });
 
  app.post('/api/file/all', controller.listAllFiles);

  app.post('/api/BidProduct/bid', controller.addBidProduct);

  app.post('/api/BidProduct/findbid', controller.listAllbidproduct);

  app.post('/api/BidProduct/MyAuctionlistAllFiles', controller.MyAuctionlistAllFiles);

  app.post('/api/BidProduct/findwinnerid', controller.findwinnerid);

  app.post('/api/BidProduct/Winnerdetalis', controller.Winnerdetalis);
  
  app.post('/api/BidProduct/WinnerdetalisProfile', controller.WinnerdetalisProfile);
 
  // app.get('/api/file/:id', fileWorker.downloadFile);

  //app.post("/api/auth/upload", upload.any("file"), uploadController.uploadFiles);
  //app.post("/api/auth/upload", upload.single("file"), uploadController.uploadFiles);

  // app.post('/api/upload', upload.array('response', 3), (req, res) => {
  //   console.log('file', req.files);
  //   console.log('body', req.body);
  //   res.status(200).json({
  //     message: 'success!',
  //   });
  // });
  // app.post('/upload',upload.single('fileData'), (req, res,next) => {
  //   console.log(req.file);//this will be automatically set by multer
  //   console.log(req.body);
  //   //below code will read the data from the upload folder. Multer     will automatically upload the file in that folder with an  autogenerated name
  //   fs.readFile(req.file.path,(err, contents)=> {
  //    if (err) {
  //    console.log('Error: ', err);
  //   }else{
  //    console.log('File contents ',contents);
  //   }
  //  });
  // });
  

};